# Generated by Django 5.0.3 on 2024-03-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField()),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(to='movie.genre')),
            ],
        ),
    ]
